//
//  Countries.swift
//  PilotLog
//
//  Created by Max Udaskin on 2024-03-17.
//

import Foundation

struct Countries {
    static let name = [
        "AF": "Afghanistan",
        "AL": "Albania",
        "DZ": "Algeria",
        "AS": "American Samoa",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguilla",
        "AQ": "Antarctica",
        "AG": "Antigua and Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BE": "Belgium",
        "BZ": "Belize",
        "BJ": "Benin",
        "BM": "Bermuda",
        "BT": "Bhutan",
        "BO": "Bolivia",
        "BA": "Bosnia and Herzegovina",
        "BW": "Botswana",
        "BR": "Brazil",
        "IO": "British Indian Ocean Territory",
        "VG": "British Virgin Islands",
        "BN": "Brunei",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "CV": "Cape Verde",
        "BQ": "Caribbean Netherlands",
        "KY": "Cayman Islands",
        "CF": "Central African Republic",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CX": "Christmas Island",
        "CC": "Cocos (Keeling) Islands",
        "CO": "Colombia",
        "KM": "Comoros",
        "CK": "Cook Islands",
        "CR": "Costa Rica",
        "CI": "Côte d'Ivoire",
        "HR": "Croatia",
        "CU": "Cuba",
        "CW": "Curaçao",
        "CY": "Cyprus",
        "CZ": "Czech Republic",
        "CD": "Democratic Republic of the Congo",
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "EE": "Estonia",
        "SZ": "Eswatini",
        "ET": "Ethiopia",
        "FK": "Falkland Islands",
        "FO": "Faroe Islands",
        "FJ": "Fiji",
        "FI": "Finland",
        "FR": "France",
        "GF": "French Guiana",
        "PF": "French Polynesia",
        "TF": "French Southern and Antarctic Lands",
        "GA": "Gabon",
        "GM": "Gambia",
        "GE": "Georgia",
        "DE": "Germany",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Greece",
        "GL": "Greenland",
        "GD": "Grenada",
        "GP": "Guadeloupe",
        "GU": "Guam",
        "GT": "Guatemala",
        "GG": "Guernsey",
        "GN": "Guinea",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haiti",
        "HM": "Heard and McDonald Islands",
        "HN": "Honduras",
        "HK": "Hong Kong",
        "HU": "Hungary",
        "IS": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran",
        "IQ": "Iraq",
        "IE": "Ireland",
        "IM": "Isle of Man",
        "IL": "Israel",
        "IT": "Italy",
        "JM": "Jamaica",
        "JP": "Japan",
        "JE": "Jersey",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KI": "Kiribati",
        "XK": "Kosovo",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Laos",
        "LV": "Latvia",
        "LB": "Lebanon",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "LI": "Liechtenstein",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MO": "Macau",
        "MG": "Madagascar",
        "MW": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "MH": "Marshall Islands",
        "MQ": "Martinique",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "YT": "Mayotte",
        "MX": "Mexico",
        "FM": "Micronesia",
        "MD": "Moldova",
        "MC": "Monaco",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MS": "Montserrat",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NC": "New Caledonia",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NF": "Norfolk Island",
        "KP": "North Korea",
        "MK": "North Macedonia",
        "MP": "Northern Mariana Islands",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PW": "Palau",
        "PS": "Palestinian Territory",
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippines",
        "PN": "Pitcairn",
        "PL": "Poland",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "CG": "Republic of the Congo",
        "RE": "Réunion",
        "RO": "Romania",
        "RU": "Russia",
        "RW": "Rwanda",
        "BL": "Saint Barthélemy",
        "SH": "Saint Helena, Ascension and Tristan da Cunha",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "MF": "Saint Martin",
        "PM": "Saint Pierre and Miquelon",
        "VC": "Saint Vincent and the Grenadines",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "São Tomé and Principe",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SX": "Sint Maarten",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "SO": "Somalia",
        "ZA": "South Africa",
        "GS": "South Georgia and the South Sandwich Islands",
        "KR": "South Korea",
        "SS": "South Sudan",
        "ES": "Spain",
        "LK": "Sri Lanka",
        "SD": "Sudan",
        "SR": "Suriname",
        "SE": "Sweden",
        "CH": "Switzerland",
        "SY": "Syria",
        "TW": "Taiwan",
        "TJ": "Tajikistan",
        "TZ": "Tanzania",
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad and Tobago",
        "TN": "Tunisia",
        "TR": "Turkey",
        "TM": "Turkmenistan",
        "TC": "Turks and Caicos Islands",
        "TV": "Tuvalu",
        "VI": "U.S. Virgin Islands",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": "United Kingdom",
        "US": "United States",
        "UM": "United States Minor Outlying Islands",
        "ZZ": "Unknown or unassigned country",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VU": "Vanuatu",
        "VA": "Vatican City",
        "VE": "Venezuela",
        "VN": "Vietnam",
        "WF": "Wallis and Futuna",
        "EH": "Western Sahara",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe"
    ]
    
    static let continent = [
          "AF": "AS",
          "AL": "EU",
          "DZ": "AF",
          "AS": "OC",
          "AD": "EU",
          "AO": "AF",
          "AI": "NA",
          "AQ": "AN",
          "AG": "NA",
          "AR": "SA",
          "AM": "AS",
          "AW": "NA",
          "AU": "OC",
          "AT": "EU",
          "AZ": "AS",
          "BS": "NA",
          "BH": "AS",
          "BD": "AS",
          "BB": "NA",
          "BY": "EU",
          "BE": "EU",
          "BZ": "NA",
          "BJ": "AF",
          "BM": "NA",
          "BT": "AS",
          "BO": "SA",
          "BA": "EU",
          "BW": "AF",
          "BR": "SA",
          "IO": "AS",
          "VG": "NA",
          "BN": "AS",
          "BG": "EU",
          "BF": "AF",
          "BI": "AF",
          "KH": "AS",
          "CM": "AF",
          "CA": "NA",
          "CV": "AF",
          "BQ": "NA",
          "KY": "NA",
          "CF": "AF",
          "TD": "AF",
          "CL": "SA",
          "CN": "AS",
          "CX": "AS",
          "CC": "AS",
          "CO": "SA",
          "KM": "AF",
          "CK": "OC",
          "CR": "NA",
          "CI": "AF",
          "HR": "EU",
          "CU": "NA",
          "CW": "NA",
          "CY": "AS",
          "CZ": "EU",
          "CD": "AF",
          "DK": "EU",
          "DJ": "AF",
          "DM": "NA",
          "DO": "NA",
          "EC": "SA",
          "EG": "AF",
          "SV": "NA",
          "GQ": "AF",
          "ER": "AF",
          "EE": "EU",
          "SZ": "AF",
          "ET": "AF",
          "FK": "SA",
          "FO": "EU",
          "FJ": "OC",
          "FI": "EU",
          "FR": "EU",
          "GF": "SA",
          "PF": "OC",
          "TF": "AF",
          "GA": "AF",
          "GM": "AF",
          "GE": "AS",
          "DE": "EU",
          "GH": "AF",
          "GI": "EU",
          "GR": "EU",
          "GL": "NA",
          "GD": "NA",
          "GP": "NA",
          "GU": "OC",
          "GT": "NA",
          "GG": "EU",
          "GN": "AF",
          "GW": "AF",
          "GY": "SA",
          "HT": "NA",
          "HM": "OC",
          "HN": "NA",
          "HK": "AS",
          "HU": "EU",
          "IS": "EU",
          "IN": "AS",
          "ID": "AS",
          "IR": "AS",
          "IQ": "AS",
          "IE": "EU",
          "IM": "EU",
          "IL": "AS",
          "IT": "EU",
          "JM": "NA",
          "JP": "AS",
          "JE": "EU",
          "JO": "AS",
          "KZ": "AS",
          "KE": "AF",
          "KI": "OC",
          "XK": "EU",
          "KW": "AS",
          "KG": "AS",
          "LA": "AS",
          "LV": "EU",
          "LB": "AS",
          "LS": "AF",
          "LR": "AF",
          "LY": "AF",
          "LI": "EU",
          "LT": "EU",
          "LU": "EU",
          "MO": "AS",
          "MG": "AF",
          "MW": "AF",
          "MY": "AS",
          "MV": "AS",
          "ML": "AF",
          "MT": "EU",
          "MH": "OC",
          "MQ": "NA",
          "MR": "AF",
          "MU": "AF",
          "YT": "AF",
          "MX": "NA",
          "FM": "OC",
          "MD": "EU",
          "MC": "EU",
          "MN": "AS",
          "ME": "EU",
          "MS": "NA",
          "MA": "AF",
          "MZ": "AF",
          "MM": "AS",
          "NA": "AF",
          "NR": "OC",
          "NP": "AS",
          "NL": "EU",
          "NC": "OC",
          "NZ": "OC",
          "NI": "NA",
          "NE": "AF",
          "NG": "AF",
          "NU": "OC",
          "NF": "OC",
          "KP": "AS",
          "MK": "EU",
          "MP": "OC",
          "NO": "EU",
          "OM": "AS",
          "PK": "AS",
          "PW": "OC",
          "PS": "AS",
          "PA": "NA",
          "PG": "OC",
          "PY": "SA",
          "PE": "SA",
          "PH": "AS",
          "PN": "OC",
          "PL": "EU",
          "PT": "EU",
          "PR": "NA",
          "QA": "AS",
          "CG": "AF",
          "RE": "AF",
          "RO": "EU",
          "RU": "EU",
          "RW": "AF",
          "BL": "NA",
          "SH": "AF",
          "KN": "NA",
          "LC": "NA",
          "MF": "NA",
          "PM": "NA",
          "VC": "NA",
          "WS": "OC",
          "SM": "EU",
          "ST": "AF",
          "SA": "AS",
          "SN": "AF",
          "RS": "EU",
          "SC": "AF",
          "SL": "AF",
          "SG": "AS",
          "SX": "NA",
          "SK": "EU",
          "SI": "EU",
          "SB": "OC",
          "SO": "AF",
          "ZA": "AF",
          "GS": "AN",
          "KR": "AS",
          "SS": "AF",
          "ES": "EU",
          "LK": "AS",
          "SD": "AF",
          "SR": "SA",
          "SE": "EU",
          "CH": "EU",
          "SY": "AS",
          "TW": "AS",
          "TJ": "AS",
          "TZ": "AF",
          "TH": "AS",
          "TL": "AS",
          "TG": "AF",
          "TK": "OC",
          "TO": "OC",
          "TT": "NA",
          "TN": "AF",
          "TR": "AS",
          "TM": "AS",
          "TC": "NA",
          "TV": "OC",
          "VI": "NA",
          "UG": "AF",
          "UA": "EU",
          "AE": "AS",
          "GB": "EU",
          "US": "NA",
          "UM": "OC",
          "ZZ": "AF",
          "UY": "SA",
          "UZ": "AS",
          "VU": "OC",
          "VA": "EU",
          "VE": "SA",
          "VN": "AS",
          "WF": "OC",
          "EH": "AF",
          "YE": "AS",
          "ZM": "AF",
          "ZW": "AF"
    ]
}
